services:
  ydns-updater:
    # image: ghcr.io/phfn/ydns_updater:main
    build: .
    container_name: ydns-updater
    restart: unless-stopped
    environment:
      - YDNS_HOST=${YDNS_HOST}
      - YDNS_USER=${YDNS_USER}
      - YDNS_PASSWORD=${YDNS_PASSWORD}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - YDNS_DEBUG=${YDNS_DEBUG} 
    env_file:
     - .env
    #  If you want to use IPv6
#     networks:
#       - ip6net
#
# networks:
#   ip6net:
#     external: true
